mapper = {
    "Bolivia": "Bolivia (Plurinational State of)",
    "Brunei": "Brunei Darussalam",
    "Car": "Central African Republic",
    "Czechia": "Czech Republic",
    "DRC": "Congo",
    "Faeroe Islands": "Faroe Islands",
    "Iran": "Iran (Islamic Republic of)",
    "Ivory Coast": "Côte d'Ivoire",
    "Moldova": "Moldova (Republic of)",
    "North Macedonia": "Macedonia (the former Yugoslav Republic of)",
    "Palestine": "Palestine, State of",
    "Russia": "Russian Federation",
    "S. Korea": "Korea (Republic Of)",
    "Saint Martin": "Saint Martin (French Part)",
    "Sint Maarten": "Saint Maarten (Dutch part)",
    "St. Barth": "Saint Barthelémy",
    "St. Vincent Grenadines": "Saint Vincent and the Grenadines",
    "Tanzania": "Tanzania, United Republic of",
    "U.S. Virgin Islands": "Virgin Islands (U.S.)",
    "Uae": "United Arab Emirates",
    "Uk": "United Kingdom of Great Britain and Northern Ireland",
    "Usa": "United States of America",
    "Venezuela": "Venezuela (Bolivarian Republic of)",
    "Vietnam": "Viet Nam"
}
